### ISSUE TITLE
Can not use it on Azure Functions because of Newtonsoft.Json version

### ISSUE THREAD

**Issue by TonyHenrique** [mercadopago/dx-dotnet#41]
I am trying to add this **mercadopago-sdk** NuGet package and use it on Azure Functions in C#.

Error		Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 WebAPI -> mercadopago-sdk 1.0.25 -> Newtonsoft.Json (>= 11.0.2) 
 WebAPI -> Microsoft.NET.Sdk.Functions 1.0.13 -> Newtonsoft.Json (= 9.0.1).

**Please configure the **mercadopago-sdk** NuGet Package to use Newtonsoft.Json (>= 9.0.1).**

**Comment by joelibaceta** [comment]
Solved on https://github.com/mercadopago/dx-dotnet/pull/45
