### ISSUE TITLE
Consulta: Esto está production-ready?

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/dx-dotnet#46]
Vengo arrastrando hace años una implementación propia del SDK de MP (básicamente porque la versión  anterior del SDK oficial era un `Dictionary<string, object>`), de la cual para ser honesto quisiera deshacerme y usar la versión oficial.

¿Esta versión del SDK está apta para su uso en producción?

Entiendo que la versión actual es `1.0.29`, lo cual indicaría que si (siguiendo el SemVer), pero siempre prefiero preguntar y no asumir.

**Comment by joelibaceta** [comment]
Hola @fberasategui, si esta es una nueva SDK parte de la iniciativa de mejorar la experiencia de integración, abstrayendo la necesidad de conocer las firmas, endpoints y mecanismos de autenticación, en clases genéricas con las cuales se puede interactuar con los recursos disponibles, la migración es hoy posible y recomendada, así como también estamos abiertos a sugerencias, pull requests  o reportes de la comunidad para mejorar esta nueva versión.
