### ISSUE TITLE
Que necesito para correr los unit tests?

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/dx-dotnet#49]
Me estan fallando la mitad de los unit tests

Con este error:

> Message: MercadoPago.MPException : "client_id" and "client_secret" can not be "null" when getting the "access_token"

![image](https://user-images.githubusercontent.com/13060549/41939101-33218e30-796b-11e8-90a0-8d6f842856c7.png)

Ya configuré las variables de entorno que encontré que se usan en el código:

![image](https://user-images.githubusercontent.com/13060549/41939561-985a0146-796c-11e8-9a5d-ddacdf446bbf.png)

**Comment by joelibaceta** [comment]
@fberasategui Gracias por el reporte, efectivamente estamos trabajando en una migración de credenciales, el fin del Test es poder usar `Customers and Cards` únicamente usando `AccessToken` lo que representa el Test, actualmente no esta pasando ya que espera aun un `Live AccessToken`, es decir uno que se obtiene a partir de `Client_Id` y `Client_Secret`.

Sobre la pregunta, efectivamente la forma en la que estas probando es la correcta, los tests son dependientes de las variables de entorno, es bueno tenerlo en cuenta para aclararlo en el README.

Saludos
