### ISSUE TITLE
Permitir que el Access Token se pueda definir para cada request

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/dx-dotnet#50]
Aprovecho el [comentario](https://github.com/mercadopago/dx-dotnet/issues/49#issuecomment-400699077) de @joelibaceta para solicitar esta mejora:

Hoy por hoy el Access Token / Live Token se definen de manera estática en la clase [SDK](https://github.com/mercadopago/dx-dotnet/blob/master/px-dotnet/SDK.cs). Esto es práctico para la mayoría de los casos, pero en este momento tengo un requerimiento puntual de un cliente que tiene múltiples fideicomisos y para cada uno maneja cuentas de MercadoPago diferentes, con lo cuál nuestro Sistema necesita definir el Token a utilizar dependiendo de qué cliente realice el pago.

Sugiero que se agregue una propiedad `AccessToken` en `MPBase` que permita definir el Access Token / Live Token (para los casos que lo requieran), y que en caso de ser null se utilice el valor estático de la clase SDK.

Con esto la línea [655](https://github.com/mercadopago/dx-dotnet/blob/master/px-dotnet/Core/MPBase.cs#L655) de `MPBase.cs` quedaría asi:

`string accessToken = this.AccessToken ?? SDK.GetAccessToken();`

Esto no afectaría la funcionalidad actual, y permitiría cubrir el caso que menciono arriba.

Estoy levantando el issue antes de hacer el cambio yo directamente, para no generar ningun overlap con cambios que estén haciendo ustedes.

**Comment by joelibaceta** [comment]
Hoy se esta trabajando en un campo llamado `UserAccessToken` que permite definir un `AccessToken` personalizado para cada instancia de un recurso en particular, lo ideal es evitar escenarios de ese tipo ya que tenemos métricas basadas en el identificador del usuario, por lo que sugerimos usar este nuevo campo o usar el Annotation `UserToken`y heredar una clase nueva para el recurso que se va a usar.

```csharp
[UserToken("AnotherAccessToken")]
public class CustomPaymentResource : Payment
end
```

**Comment by fberasategui** [comment]
Ok. Sería bueno dejar abierto este issue hasta que haya un release con esa mejora, así puedo sacar el SDK propio del proyecto de este cliente y usar el oficial.

Con respecto a los atributos y el uso tan fuerte de reflection que tiene este codebase estoy abriendo un issue aparte a modo de discussion.

**Comment by joelibaceta** [comment]
Ups issue cerrado no intencionalmente, reabierto

**Comment by nsabaj95** [comment]
Estamos intentando implementar MercadoPago Connect a un proyecto de .NET y entendemos que por este issue no es posible hacerlo ya que necesitamos modificar el access token de forma dinámica en cada pago realizado.
Siendo el access token una propiedad estática del SDK, corremos el riesgo de que se crucen los tokens cuando dos users hacen pagos a la vez.
También sabemos que los tokens de connect son dinámicos y no podemos estar cambiando continuamente el código o los atributos de las clases cada vez que una notificación nos indica una nueva autorización.
¿Me explico? ¿Hay alguna solución temporal para este issue que no sea la del UserAccessToken?

**Comment by fberasategui** [comment]
@nsabaj95 he realizado una serie de PRs solucionando este y varios otros issues y con varias mejoras  pero no he recibido respuesta del equipo de MercadoPago.

Te dejo el link al branch donde hice las ultimas mejoras: https://github.com/fberasategui/dx-dotnet/tree/NewIpnHandler

En una de esas te sirve...

**Comment by nsabaj95** [comment]
@fberasategui muchísimas gracias! lo vamos a probar, pero queremos intentar no salirnos de las versiones oficiales de MP ya que si sale una nueva, integrarla tal vez sea complicado. Venimos peleando con este tema de hace mucho y no obtenemos ninguna respuesta de soporte.

**Comment by fberasategui** [comment]
@nsabaj95 Yo en la medida de lo posible he mantenido mis PRs up-to-date con las modificaciones en `master`. De hecho hay funcionalidad en mi versión que no está en `master`, porque la copié y la adapté del código del SDK de java, por ejemplo [`IdentificationType`](https://github.com/fberasategui/dx-dotnet/blob/NewIpnHandler/px-dotnet/Resources/IdentificationType.cs).

**Comment by joelibaceta** [comment]
@fberasategui @nsabaj95 Disculpen la falta de respuesta estuvimos algo ocupados estos días por aquí, en esta semana estaria tomando estos PR e Issues. Saludos

**Comment by nsabaj95** [comment]
@fberasategui Perfecto! Muchas gracias

@joelibaceta No hay problema. Por favor, manténgannos al tanto ya que si no lo corrigen ustedes, tendremos que buscar la manera nosotros de hacerlo funcionar de alguna manera o utilizar el branch que pasó @fberasategui 

Saludos

**Comment by fberasategui** [comment]
@joelibaceta por las dudas aclaro: los PRs que fui levantando son todos incrementales y parten del anterior.

Es decir, https://github.com/mercadopago/dx-dotnet/pull/58 incluye todo lo de https://github.com/mercadopago/dx-dotnet/pull/57 y agrega mejoras, y éste a su vez incluye todo lo del https://github.com/mercadopago/dx-dotnet/pull/55.

Para este issue puntual se necesita incorporar https://github.com/mercadopago/dx-dotnet/pull/55, que a su vez también cierra los issues https://github.com/mercadopago/dx-dotnet/issues/48, https://github.com/mercadopago/dx-dotnet/issues/52 y https://github.com/mercadopago/dx-dotnet/issues/50

**Comment by fberasategui** [comment]
@nsabaj95 ante la falta de respuesta de la gente de MP, nosotros hemos publicado una versión extraoficial:

https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk

ya está disponible en Nuget para descargar.

Este issue está resuelto en nuestra versión.

Saludos

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-dotnet/releases/tag/1.0.42

**Comment by monkjuice** [comment]
@joelibaceta Pregunto aprovechando este thread; se va a hacer el mismo desarrollo que este pero para el caso de "Checkout Basico"? Donde necesitamos ClientId y ClientSecret

**Comment by joelibaceta** [comment]
@monkjuice este desarrollo en particular trata de añadir soporte para escenarios de Marketplace, en el que para un pago en particular necesitas decir que este sea procesado para una subtienda, usando sus propios accesstoken, esto afecta a todas las entidades desde preferencias a pagos.

Actualmente el fin no es exactamente permitir cambiar las credenciales durante el ciclo de vida de la aplicación, sino permitir que una transacción en particular use un access_token sin cambiar el flujo de la aplicación.

**Comment by nsabaj95** [comment]
En la versión 1.0.42 intento hacer un pago indicando el marketplace_access_token y recibo el error: "The name of the following parameters is wrong : [marketplace_access_token]". Por favor nececesitamos que esto esté solucionado.
