### ISSUE TITLE
Sugerencia: Evitar el uso de reflection

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/dx-dotnet#52]
En general se desalienta el uso de reflection para resolver problemas para los cuales existen soluciones a nivel de lenguaje o Framework.

Doy un ejemplo concreto:

Qué ventaja o valor agregado ofrece este approach:

```C#
[GETEndpoint("/v1/payments/:id")]
public static Payment FindById(int? id, bool useCache)
{
    return (Payment)ProcessMethod<Payment>(typeof(Payment), "FindById", id.ToString(), useCache);
} 
```

comparado con este:

```C#
public static Payment FindById(int id, bool useCache)
{
    return Get<Payment>($"/v1/payments/{id}", useCache);
} 
```

Nótese que usando [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) se genera el string final de manera práctica.  

De la misma forma, usando [optional arguments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments) se pueden especificar los valores para `requestTimeout` y `retries`:

```C#
internal static T Get<T>(string endpoint, bool useCache = false, int requestTimeout = 0, int retries = 0)
{
    //...
}
```

Entiendo que otras plataformas o lenguajes no poseen estas ventajas, pero en C#/.NET es muy común su uso. 

El uso de reflection, en cambio, ofusca la intención del código, disminuye el type safety, y en general hace que el código sea menos mantenible.

**Comment by joelibaceta** [comment]
@fberasategui te comento algunos de los objetivos que buscamos con el SDK.

**Externos**
- Ser idiomatico y familiar para el integrador afin a una tecnologica en particular.
- Abstraer la interacción con los endpoints públicos del API, evitando la necesidad de conocer la estructura y respuesta del mismo.
- Centralizar el mantenimiento y reducir el impacto ante cambios de firma de los APIs.
- Forzar buenas practicas al comunicarse con nuestro API (Idempotencia, Headers, etc) 

**Internos**
- Facilitar el mantenimiento y actualización de las clases finales con el fin de estar alineados con los cambios frecuentes de los APIS, incluso por operadores no técnicos.

Bajo esta logica se desprende una premisa que se repite en los SDKs de otros lenguajes, tener clases finales _**descriptivas**_ que permitan un mantenimiento (_Cambio de firma, añadir campos o crear nuevas clases para nuevos recursos del API_) que no requieran mayores Skills Técnicos, Lo que nos llevo a exportar toda la lógica a una clase única representativa MPBase retirándo lo mas posible lógica en clases como Payment o Preference.

También es importante destacar que existe una deuda técnica generada durante el camino de puesta a producción de este SDK desde su conceptualización, con el fin de tratar de soportar todos los escenarios que se pueden presentar durante una integración para los cuales todo aporte de refactorizacion es bienvenido.

**Sobre el issue en particular:**

`ProcessMethod` es un metodo generico de la clase abstracta `MPBase` el cual por definición encierra toda la `logica compleja` que podría usar alguna clase que represente un recurso de un API expuesto, por lo que el uso y quizás abuso de reflection en esta clase se debe a la búsqueda de los siguientes objetivos:

- Separar la "Descripción" del método de la lógica del mismo, en las clases recurso (_Para desalentar su modificación_) y permitir un fácil _copy&paste_ para el mantenimiento, desde operadores no técnicos.
- No pedir ningún atributo que pueda ser "**adivinado**" ( Sea informacion genérica, como el nombre de la clase, o los atributos de la instancia que esta llamando a este método)
- Se debe automatizar lo mas posible la construcción de urls finales, para casos como **FindByID** es fácil pensar en solicitar como parámetro el ID pero existen escenarios en los que hay atributos de otro tipo en la url, como para `Cards`, para obtener informacion sobre una tarjeta guardada en particular, se debe usar /v1/customers/**:customer_id**/cards/**:id** en el que se debe "adivinar" el valor de `:customer_id` a partir de los atributos de la instancia de Customer para quien se piden las tarjetas.
- Poder soportar futuros metodos genericos no CRUD (Como refund(), para Payments, que encapsule un POST a un sub endpoint como **/v1/payments/:id/refunds**

Tambien, aprovecho para revisar un histórico sobre la evolución de los `annotations`, durante el proceso de diseño, se buscaba una clase que pueda ser mas descriptiva. (Abstrayendo totalmente los métodos, llevándolos a la Clase Abstracta), facilitando al máximo su mantenimiento.

```csharp
[GET("/v1/payments/:id")]
[POST("/v1/payments/")]
[PUT("/v1/payments/:id")]
public class Payment : MPBase
{
    private long? _id;
    private Payer _payer;
    private string _token;
   /// ...
}
```

Con un output similar a:

```csharp
Payment payment = new Payment 
{
    TransactionAmount = (float)20.0,
    Description = "Pago de Prueba",
    PaymentMethodId = "visa"
};

payment.Save(); // Esto usaría el endpoint definido en POST
```

```csharp
payment.Status =  PaymentStatus.cancelled;

/// Esto usaría el endpoint definido en PUT 
/// ("Adivinando" el parámetro :id requerido en el path del endpoint)
payment.Update(); 
```

**Problemas que observamos mejorables sobre el status actual:**
- Refactorizar la forma en la que se define un `método` del recurso API y su asociación con un metodo genérico de tipo ORM ( Save, Update, Delete, All, Find ).
- Legibilidad del código centralizado en MPBase.  


## Resumen

Luego de revisar lo expuesto anteriormente dejo abierta la discusión para encontrar la mejor forma de resolver las necesidades existentes teniendo en cuenta las buenas practicas de .net y generar código de calidad, haciendo un giro de perspectiva desde nuestro primer _approach_ de diseño.

**Comment by fberasategui** [comment]
@joelibaceta alguna novedad de esto? vale la pena que vuelva a abrir los PRs?
