### ISSUE TITLE
Web Tokenized Checkout - Procesar Respuesta

### ISSUE THREAD

**Issue by nataliacorinadiaz** [mercadopago/dx-dotnet#64]
Buenas tardes, estoy utilizando la opción Web Tokenized Checkout. 
Inmediatamente después de la creación del pago puedo consultar el Status del mismo (hasta ahí funciona todo bien), pero... 
- ¿Que pasa cuando el estado es "Pendiente"? 
- ¿Se supone que recibiré la notificación segun el "notification-url" cuando haya alguna novedad? 

Hasta ahora no me esta llegando ninguna notificación para los pagos que creo. Estoy usando mi access-token de test para las pruebas, y para el comprador solo envió como dato un mail, que segun entiendo no es necesario ni siquiera que este registrado en MP, ya que la creación de pago con los datos de prueba de las tarjetas que figuran en la pagina de MP-developers estaria funcionando. 

Agrego el código donde genero el pago, por si me esta faltando alguna configuración:

                   SDK.SetAccessToken(mp.AccessToken);
               
                    Payment payment = new Payment()
                    { 
                        NotificationUrl = "http://190.105.227.170:8080/api/notificacionespago",
                        TransactionAmount = (float)pago.ImporteTotal,
                        Token = pago.MPToken,
                        Description = "Pago de cuotas seleccionadas",
                        Installments = pago.MPCuotas,
                        PaymentMethodId = pago.MPMetodo,
                        IssuerId = pago.MPEmisor,
                        Payer = new Payer()
                        { //eMail del usuario admin del cliente
                              Email = cliSrv.ObtenerUsuario(pago.IdCliente).EMail
                        }
                    };
                
                    // Guarda y postea el pago
                    payment.Save();

                    // proceso para asentar el pago
                    if (payment.Status == MercadoPago.Common.PaymentStatus.approved)
....

**Comment by joelibaceta** [comment]
@nataliacorinadiaz Este es un canal para reportar bugs o errores en el código del SDK de .net, para recibir soporte sobre el proceso de integración o errores de otros productos puedes usar el canal de soporte oficial: [http://www.mercadopago.com.ar/developers/es/support](http://www.mercadopago.com.ar/developers/es/support)
