### ISSUE TITLE
Newtonsoft SnakeCaseNaming bug

### ISSUE THREAD

**Issue by monkjuice** [mercadopago/dx-dotnet#68]
Al postear una nueva preferencia que contenga "Payer" este se envía en el body del json como `"Payer:"` en vez de `"payer:"`; el endpoint es case-sensitive y por lo tanto la entidad Payer no es guardada con la preferencia. 

**Para reproducir**

Aprovechamos el "Trace.WriteLine" de MPRESTClient existente en la linea 59 y guardamos una preferencia que contenga como atributos "Items" y un "Payer". Al "POSTearlo" con el metodo save() vemos como resultado el siguiente JSON:

`'{"Payer": {"email": "fake@mail.com"},"items": [  { "id": "1", "title": "Transaccion","quantity": 1,  "currency_id": "ARS","unit_price": 1.00 } ]}'
`

Esto es de vital importancia para nosotros ya que la preferencia según pude observar no necesita un payer para ser guardada; pero si necesitas iniciar el checkout desde una preferencia en android, no te lo permite; devuelve error al no tener "payer" la preferencia.

**env**
 - OS: Windows 10 x64
 - .NET: 4.5

**Comment by monkjuice** [comment]
Esto se soluciona utilizando `CamelCaseNamingStrategy` en el serializer de MPCoreUtils.cs

**Comment by joelibaceta** [comment]
@monkjuice ¿Que version del SDK estas usando?, corregimos un bug con la serialización en la versión 1.0.40

**Comment by monkjuice** [comment]
> @monkjuice ¿Que version del SDK estas usando?, corregimos un bug con la serialización en la versión 1.0.40

Perfecto! Se resolvio tal como dijiste haciendo un upgrade
