### ISSUE TITLE
Marketplace Refund Unauthorized use of live credentials

### ISSUE THREAD

**Issue by mg9101** [mercadopago/dx-dotnet#70]
Necesito realizar un refund desde una aplicación que es MarketPlace, pero me tira el siguiente error
{"message":"Unauthorized use of live credentials","error":"unauthorized","status":401,"cause":[{"code":7,"description":"Unauthorized use of live credentials","data":null}]}

El código es el siguiente:

        If MercadoPago.SDK.ClientId = "" Then
            MercadoPago.SDK.ClientId = "client_id"
            MercadoPago.SDK.ClientSecret = "client_secret"
        End If

        Dim payment As New MercadoPago.Resources.Payment
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        payment = MercadoPago.Resources.Payment.FindById("payment_id")
        payment.Refund()

**Comment by joelibaceta** [comment]
Debes usar un AccessToken en lugar de ClientId y ClientSecret.

**Comment by mg9101** [comment]
Pero si uso el access token del usuario que cobró, se descuenta el importe cobrado por la comisión del Marketplace_fee?

**Comment by mg9101** [comment]
Usando el access_token da el mismo error, nuestro proyecto es con checkout básico, no con personalizado

**Comment by joelibaceta** [comment]
@mg9101 solo se usa `live_credentials` ( client_id + client_secret ) para la creación de preferencias, para operar con pagos se usan `access_token`

**Comment by hperezbaranda** [comment]
A ustedes les funciona de esa forma?
`var payment = MercadoPago.Resources.Payment.FindById("payment_id")`

 Porque lo estoy probando y estoy usando  AccessToken en lugar de ClientId y ClientSecret, pero me devuelve un error interno de mercadopago:

> Could not load type 'System.Web.HttpRuntime' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Estoy usando la SDK de C# la ultima version

**Comment by mg9101** [comment]
@hperezbaranda 
Para el TLS es esta linea: 
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Y el target framework en el web.config tiene que ser minimo 4.5,  targetFramework="4.5"

**Comment by hperezbaranda** [comment]
Si esa linea ya la use y nada continua con el error, y el framework que estoy usando es .Net Core 2.1.

**Comment by fberasategui** [comment]
@hperezbaranda este SDK no soporta .NET Core.

Podes usar el SDK extraoficial de [Lexim](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk).

**Comment by hperezbaranda** [comment]
@fberasategui Lo probare de nuevo, pero cuando lo hice, es cierto que no me da ese problema, pero no me funcionó la sentencia 
`var payment = MercadoPago.Resources.Payment.FindById("payment_id")`

**Comment by fberasategui** [comment]
@hperezbaranda si encontras algun error en nuestro SDK, podes levantar un [issue](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/issues). En principio el workflow de payments (en sus distintas variantes) funciona bien usando nuestro SDK, y podés usarlo en proyectos de .NET Core, cosa que el oficial no, ya que depende de `System.Web`, que no existe en .NET Core.
