### ISSUE TITLE
Error al ejecutar cualquier .Save() en los objetos del SDK con c#

### ISSUE THREAD

**Issue by DanielAdinco** [mercadopago/dx-dotnet#80]
Hola buenas noches,

No he podido ejecutar pruebas en mi aplicación web, cada vez que intento ejecutar cualquier método Save , por ejemplo en el Payment, me arroja el siguiente error (ya verifiqué el Public key,Access token, CLIENT_SECRET y CLIENT_ID ):

		_ex.StackTrace	"   en MercadoPago.MPRESTClient.ExecuteRequest(HttpMethod httpMethod, String path, PayloadType payloadType, JObject payload, WebHeaderCollection colHeaders, Int32 requestTimeout, Int32 retries)\r\n   en MercadoPago.MPBase.CallAPI(HttpMethod httpMethod, String path, PayloadType payloadType, JObject payload, WebHeaderCollection colHeaders, Boolean useCache, Int32 requestTimeout, Int32 retries)\r\n   en MercadoPago.MPBase.ProcessMethod[T](Type clazz, T resource, String methodName, Dictionary`2 parameters, Boolean useCache)\r\n   en MercadoPago.MPBase.ProcessMethodBool[T](String methodName, Boolean useCache)\r\n   en MercadoPago.Resources.Payment.Save()\r\n   en MasZapatos.Business.MercadoPagoBusiness.realizarPago(CarritoListViewModel carrito, String tokenId, String mediPago, Int32 installments, String issuer_id)_ 

El código que intento ejecutar es el siguiente:

 Payment payment = new Payment()
                {
                    TransactionAmount = float.Parse(carrito.total.ToString()),
                    Token = tokenId,
                    Description = "Pedido de zapatos Mas y Mas Zapatos Folio:" + carrito.id + " uuid:"+carrito.uuid,
                    Installments = installments,
                    PaymentMethodId = mediPago,
                    IssuerId = issuer_id,
                    Payer = new Payer()
                    {
                        Email = carrito.emailUser
                    }
                };
                // Guarda y postea el pago
                payment.Save();

**Comment by DanielAdinco** [comment]
Ya pude solucionarlo, especifiqué el protocolo de seguridad con está linea:

 ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;-- TLS 1.2

**Comment by joelibaceta** [comment]
@DanielAdinco Esto se debe a que MercadoPago dejo de soportar protocolos inferiores a TLS 1.2.
